"""schedule model changed again

Revision ID: 2f59705205f2
Revises: 662595781079
Create Date: 2024-05-19 19:00:24.749157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2f59705205f2'
down_revision: Union[str, None] = '662595781079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule') as batch_op:
        batch_op.alter_column('time',
                              existing_type=sa.DATE(),
                              type_=sa.DateTime(),
                              existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'time',
                    existing_type=sa.DateTime(),
                    type_=sa.DATE(),
                    existing_nullable=False)
    # ### end Alembic commands ###
