"""users model changed

Revision ID: 51bd5b39796b
Revises: cfbf779cd5ad
Create Date: 2024-05-19 19:33:08.092515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51bd5b39796b'
down_revision: Union[str, None] = 'cfbf779cd5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_column('tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
