"""schedule model fix

Revision ID: cfbf779cd5ad
Revises: 2f59705205f2
Create Date: 2024-05-19 19:11:00.161156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfbf779cd5ad'
down_revision: Union[str, None] = '2f59705205f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule') as batch_op:
        batch_op.alter_column('time',
                              existing_type=sa.DATETIME(),
                              type_=sa.String(),
                              existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'time',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
